FROM php:8.2.29-fpm

ENV PHP_SERVER=1

RUN apt update && apt install -y \
    curl \
    nodejs npm \
    zip \
    unzip \
    libzip-dev

RUN docker-php-ext-install \
    pdo \
    pdo_mysql \
    mysqli \
    zip
    

COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY docker/init_app_entrypoint.sh /usr/local/bin/init_app_entrypoint.sh

RUN chmod 777 -R /var/www/html
RUN chmod 777 /usr/local/bin/init_app_entrypoint.sh

WORKDIR /var/www/html

ENTRYPOINT ["/usr/local/bin/init_app_entrypoint.sh"]
CMD ["php-fpm"]
# RUN composer update
# RUN composer install
# RUN npm install
# RUN npm run build
# RUN php artisan key:generate
# RUN php artisan migrate:fresh --seed